// places, ideas, people, politics, science, art
const pages = {
  places: [
    'Amsterdam',
    'Athens',
    'Baghdad',
    'Bangkok',
    'Beijing',
    'Berlin',
    'Bogotá',
    'Brussels',
    'Buenos Aires',
    'Cairo',
    'Cape Town',
    'Damascus',
    'Delhi',
    'Dhaka',
    'Dubai',
    'Hong Kong',
    'Istanbul',
    'Jakarta',
    'Jerusalem',
    'Karachi',
    'Kinshasa',
    'Kolkata',
    'Lagos',
    'London',
    'Los Angeles',
    'Madrid',
    'Mecca',
    'Mexico City',
    'Moscow',
    'Mumbai',
    'Nairobi',
    'New York City',
    'Paris',
    'Rio de Janeiro',
    'Rome',
    'Saint Petersburg',
    'São Paulo',
    'Seoul',
    'Shanghai',
    'Sydney',
    'Tehran',
    'Tokyo',
    'Vienna',
    'Washington, D.C.',
    'Afghanistan',
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Bangladesh',
    'Brazil',
    'Canada',
    'China',
    'Democratic Republic of the Congo',
    'Cuba',
    'Egypt',
    'Ethiopia',
    'France',
    'Germany',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'New Zealand',
    'Nigeria',
    'Pakistan',
    'Poland',
    'Portugal',
    'Russia',
    'Saudi Arabia',
    'Singapore',
    'South Africa',
    'South Korea',
    'Spain',
    'Sudan',
    'Switzerland',
    'Tanzania',
    'Thailand',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'United States',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Geography',
    'City',
    'Continent',
    'Forest',
    'Mountain',
    'Desert',
    'North Pole',
    'Ocean',
    'River',
    'Sea',
    'South Pole',
    'Africa',
    'Antarctica',
    'Asia',
    'Europe',
    'Middle East',
    'North America',
    'Oceania',
    'South America',
    'Angkor Wat',
    'Colosseum',
    'Great Wall of China',
    'Eiffel Tower',
    'Empire State Building',
    'Hagia Sophia',
    'Parthenon',
    'Giza Necropolis',
    'St. Peter\'s Basilica',
    'Statue of Liberty',
    'Taj Mahal',
    'Three Gorges Dam',


    'Africa',
    'Antarctica',
    'Asia',
    'Europe',
    'Middle East',
    'North America',
    'Oceania',
    'South America',
    'Amazon River',
    'Arctic Ocean',
    'Atlantic Ocean',
    'Baltic Sea',
    'Black Sea',
    'Caribbean Sea',
    'Caspian Sea',
    'Congo River',
    'Danube',
    'Ganges',
    'Great Barrier Reef',
    'Great Lakes',
    'Indian Ocean',
    'Indus River',
    'Lake Baikal',
    'Lake Tanganyika',
    'Lake Victoria',
    'Mediterranean Sea',
    'Mississippi River',
    'Niger River',
    'Nile',
    'North Sea',
    'Pacific Ocean',
    'Panama Canal',
    'Rhine',
    'Suez Canal',
    'Southern Ocean',
    'Volga River',
    'Yangtze River',
    'Yellow River',
    'Alps',
    'Andes',
    'Himalayas',
    'Mount Everest',
    'Mount Kilimanjaro',
    'Rocky Mountains',
    'Sahara'
  ],

  concepts: [
    'Politics',
    'Anarchism',
    'Colonialism',
    'Communism',
    'Conservatism',
    'Democracy',
    'Dictatorship',
    'Diplomacy',
    'Fascism',
    'Globalization',
    'Government',
    'Ideology',
    'Imperialism',
    'Liberalism',
    'Marxism',
    'Monarchy',
    'Nationalism',
    'Republic',
    'Socialism',
    'State (polity)',
    'Political party',
    'Propaganda',
    'Terrorism',
    'Society',
    'Civilization',
    'Education',
    'Family',
    'Child',
    'Man',
    'Marriage',
    'Woman',
    'Beauty',
    'Dialectic',
    'Ethics',
    'Epistemology',
    'Feminism',
    'Free will',
    'Knowledge',
    'Logic',
    'Mind',
    'Philosophy',
    'Probability',
    'Reality',
    'Truth',
    'Behavior',
    'Emotion',
    'Love',
    'Psychology',
    'Thought',
    'Athletics',
    'Auto racing',
    'Baseball',
    'Basketball',
    'Cricket',
    'Association football',
    'Golf',
    'Rugby',
    'Tennis',
    'Gambling',
    'Martial arts',
    'Karate',
    'Judo'
  ],

  people: [
    'Akbar',
    'Alexander the Great',
    'Ashoka',
    'Atatürk, Mustafa Kemal',
    'Augustus',
    'von Bismarck, Otto',
    'Bolívar, Simón',
    'Bonaparte, Napoleon',
    'Caesar, Julius',
    'Charlemagne',
    'Churchill, Winston',
    'Constantine the Great',
    'Cyrus the Great',
    'de Gaulle, Charles',
    'Elizabeth I of England',
    'Gandhi, Mohandas Karamchand',
    'Genghis Khan',
    'Guevara, Che',
    'Hitler, Adolf',
    'Joan of Arc',
    'King, Martin Luther, Jr.',
    'Lenin, Vladimir',
    'Lincoln, Abraham',
    'Louis XIV',
    'Luxemburg, Rosa',
    'Mandela, Nelson',
    'Mao Zedong',
    'Nehru, Jawaharlal',
    'Nkrumah, Kwame',
    'Peter the Great',
    'Qin Shi Huang',
    'Roosevelt, Franklin D.',
    'Saladin',
    'Stalin, Joseph',
    'Suleiman the Magnificent',
    'Sun Yat-sen',
    'Tamerlane',
    'Umar',
    'Washington, George',
    'Abraham',
    'Aquinas, Thomas',
    'Augustine of Hippo',
    'Buddha',
    'Al-Ghazali',
    'Jesus',
    'Luther, Martin',
    'Moses',
    'Muhammad',
    'Paul the Apostle',
    'Bernhardt, Sarah',
    'Chaplin, Charlie',
    'Dietrich, Marlene',
    'Monroe, Marilyn',
    'Le Corbusier',
    'Dalí, Salvador',
    'Dürer, Albrecht',
    'Gogh, Vincent van',
    'Goya, Francisco de',
    'Hokusai, Katsushika',
    'Kahlo, Frida',
    'Leonardo da Vinci',
    'Matisse, Henri',
    'Michelangelo',
    'Picasso, Pablo',
    'Raphael',
    'Rembrandt',
    'Rubens, Peter Paul',
    'Sinan, Mimar',
    'Velázquez, Diego',
    'Warhol, Andy',
    'Wright, Frank Lloyd',
    'Abu Nuwas',
    'Andersen, Hans Christian',
    'Bashō',
    'Borges, Jorge Luis',
    'Byron, George',
    'Cervantes, Miguel de',
    'Chaucer, Geoffrey',
    'Chekhov, Anton',
    'Dante Alighieri',
    'Dickens, Charles',
    'Dostoyevsky, Fyodor',
    'García Márquez, Gabriel',
    'Goethe, Johann Wolfgang von',
    'Hafez',
    'Homer',
    'Hugo, Victor',
    'Joyce, James',
    'Kafka, Franz',
    'Kālidāsa',
    'Li Bai',
    'Naguib Mahfouz',
    'Molière',
    'Ovid',
    'Proust, Marcel',
    'Pushkin, Alexander',
    'Shakespeare, William',
    'Sophocles',
    'Tagore, Rabindranath',
    'Tolstoy, Leo',
    'Twain, Mark',
    'Virgil',
    'Armstrong, Louis',
    'Bach, Johann Sebastian',
    'Beatles, The',
    'Beethoven, Ludwig van',
    'Brahms, Johannes',
    'Chopin, Frédéric',
    'Dvořák, Antonín',
    'Handel, Georg Frideric',
    'Haydn, Joseph',
    'Mahler, Gustav',
    'Mozart, Wolfgang Amadeus',
    'Palestrina, Giovanni Pierluigi da',
    'Piaf, Édith',
    'Presley, Elvis',
    'Puccini, Giacomo',
    'Schubert, Franz',
    'Stravinsky, Igor',
    'Tchaikovsky, Petr',
    'Verdi, Giuseppe',
    'Vivaldi, Antonio',
    'Wagner, Richard',
    'Amundsen, Roald',
    'Armstrong, Neil',
    'Cartier, Jacques',
    'Columbus, Christopher',
    'Cook, James',
    'Cortés, Hernán',
    'Gagarin, Yuri',
    'da Gama, Vasco',
    'Ibn Battuta',
    'Magellan, Ferdinand',
    'Polo, Marco',
    'Zheng He',
    'Bergman, Ingmar',
    'Disney, Walt',
    'Eisenstein, Sergei',
    'Fellini, Federico',
    'Hitchcock, Alfred',
    'Kubrick, Stanley',
    'Kurosawa, Akira',
    'Ray, Satyajit',
    'Spielberg, Steven',
    'Archimedes',
    'Avicenna',
    'Berners-Lee, Tim',
    'Brahmagupta',
    'Copernicus, Nicolaus',
    'Curie, Marie',
    'Darwin, Charles',
    'Edison, Thomas',
    'Einstein, Albert',
    'Euclid',
    'Euler, Leonhard',
    'Faraday, Michael',
    'Fermi, Enrico',
    'Ford, Henry',
    'Galen',
    'Galileo Galilei',
    'Gauss, Carl Friedrich',
    'Gutenberg, Johannes',
    'Hilbert, David',
    'Joule, James Prescott',
    'Kepler, Johannes',
    'al-Khwarizmi, Muhammad ibn Musa',
    'Leibniz, Gottfried Wilhelm',
    'Linnaeus, Carl',
    'Maxwell, James Clerk',
    'Mendeleev, Dmitri',
    'Newton, Sir Isaac',
    'Pasteur, Louis',
    'Planck, Max',
    'Rutherford, Ernest',
    'Schrödinger, Erwin',
    'Tesla, Nikola',
    'Turing, Alan',
    'Watt, James',
    'Aristotle',
    'Beauvoir, Simone de',
    'Chanakya',
    'Chomsky, Noam',
    'Confucius',
    'Descartes, René',
    'Freud, Sigmund',
    'Hegel, Georg Wilhelm Friedrich',
    'Ibn Khaldun',
    'Kant, Immanuel',
    'Keynes, John Maynard',
    'Laozi',
    'Locke, John',
    'Machiavelli, Niccolò',
    'Marx, Karl',
    'Nietzsche, Friedrich',
    'Plato',
    'Rousseau, Jean-Jacques',
    'Sartre, Jean-Paul',
    'Sima Qian',
    'Smith, Adam',
    'Socrates',
    'Voltaire',
    'Weber, Max',
    'Wittgenstein, Ludwig',
    'Zhu Xi',
  ],

  politics: [
    'African Union',
    'Arab League',
    'ASEAN',
    'Commonwealth of Independent States',
    'Commonwealth of Nations',
    'European Union',
    'International Red Cross and Red Crescent Movement',
    'NATO',
    'Nobel Prize',
    'OPEC',
    'United Nations',
    'World Bank',
    'World Trade Organization',
    'Civil war',
    'Military',
    'Peace',
    'War',
    'Abortion',
    'Capital punishment',
    'Human rights',
    'Racism',
    'Slavery',

    'Prehistory',
    'Stone Age',
    'Bronze Age',
    'Iron Age',
    'Mesopotamia',
    'Ancient Egypt',
    'Ancient Greece',
    'Roman Empire',
    'Han Dynasty',
    'Gupta Empire',
    'Abbasid Caliphate',
    'Age of Enlightenment',
    'Aztec',
    'Byzantine Empire',
    'Crusades',
    'Holy Roman Empire',
    'Hundred Years\' War',
    'Middle Ages',
    'Mongol Empire',
    'Ming Dynasty',
    'Ottoman Empire',
    'Protestant Reformation',
    'Thirty Years\' War',
    'Renaissance',
    'Tang Dynasty',
    'Vikings',
    'Arab-Israeli conflict',
    'American Civil War',
    'Apartheid',
    'British Empire',
    'Cold War',
    'Cultural Revolution',
    'French Revolution',
    'Great Depression',
    'The Holocaust',
    'Industrial Revolution',
    'Nazi Germany',
    'Meiji Restoration',
    'Russian Revolution',
    'Qing Dynasty',
    'Treaty of Versailles',
    'Vietnam War',
    'World War I',
    'World War II',
  ],

  science: [
    'Science',
    'Nature',
    'Astronomy',
    'Asteroid',
    'Big Bang',
    'Black hole',
    'Comet',
    'Galaxy',
    'Milky Way',
    'Moon',
    'Planet',
    'Earth',
    'Jupiter',
    'Mars',
    'Mercury',
    'Neptune',
    'Saturn',
    'Uranus',
    'Venus',
    'Solar System',
    'Spaceflight',
    'Star',
    'Sun',
    'Universe',
    'Metabolism',
    'Digestion',
    'Photosynthesis',
    'Breathing',
    'Evolution',
    'Reproduction',
    'Pregnancy',
    'Sex',
    'Anatomy',
    'Breast',
    'Cell',
    'Circulatory system',
    'Blood',
    'Heart',
    'Endocrine system',
    'Human gastrointestinal tract',
    'Large intestine',
    'Small intestine',
    'Liver',
    'Muscle',
    'Nervous system',
    'Brain',
    'Nerve',
    'Sensory system',
    'Ear',
    'Nose',
    'Eye',
    'Reproductive system',
    'Respiratory system',
    'Skeleton',
    'Skin',
    'Medicine',
    'Addiction',
    'Ethanol',
    'Tobacco',
    'Alzheimer\'s disease',
    'Cancer',
    'COPD',
    'Common cold',
    'Dentistry',
    'Disability',
    'Blindness',
    'Deafness',
    'Mental disorder',
    'Disease',
    'Epilepsy',
    'Pharmaceutical drug',
    'Antibiotic',
    'Health',
    'Gastroenteritis',
    'Headache',
    'Heart attack',
    'Immune system',
    'Malaria',
    'Malnutrition',
    'Menstruation',
    'Obesity',
    'Pandemic',
    'Pneumonia',
    'Poliomyelitis',
    'Sexually transmitted disease',
    'AIDS',
    'Stroke',
    'Tuberculosis',
    'Diabetes mellitus',
    'Virus',
    'Influenza',
    'Smallpox',
    'Camel',
    'Cat',
    'Cattle',
    'Dog',
    'Elephant',
    'Horse',
    'Sheep',
    'Rodent',
    'Domestic pig',
    'Primate',
    'Shark',
    'Carbon',
    'Copper',
    'Gold',
    'Hydrogen',
    'Iron',
    'Nitrogen',
    'Oxygen',
    'Silver',
    'Flood',
    'Tsunami',
    'Volcano',
    'Weather',
    'Cloud',
    'Rain',
    'Snow',
    'Tornado',
    'Tropical cyclone',
    'Wind',
    'Quantum mechanics',
    'Radioactive decay',
    'General relativity',
    'Special relativity',
    'Semiconductor',
    'Angle',
    'Area',
    'Coordinate system',
    'Pi',
    'Pythagorean theorem',
    'Symmetry',
    'Trigonometry',
    'Cotton',
    'Robot',
    'Encyclopedia',
    'Internet',
    'Email',
    'World Wide Web',
    'Operating system',
    'Programming language',
    'Software',
    'Glass',
    'Paper',
    'Plastic',
    'Wood',
    'Transport',
    'Aircraft',
    'Automobile',
    'Bicycle',
    'Submarine',
    'Ship',
    'Train',
    'Food',
    'Bread',
    'Cereal',
    'Barley',
    'Maize',
    'Oat',
    'Rice',
    'Rye',
    'Sorghum',
    'Wheat',
    'Cheese',
    'Chocolate',
    'Honey',
    'Fruit',
    'Apple',
    'Banana',
    'Grape',
    'Soybean',
    'Lemon',
    'Nut (fruit)',
    'Meat',
    'Sugar',
    'Vegetable',
    'Potato',
    'Beer',
    'Coffee',
    'Juice',
    'Milk',
    'Tea',
    'Water',
    'Wine',
  ],

  art: [
    'Blues',
    'Classical music',
    'Opera',
    'Symphony',
    'Electronic music',
    'Flamenco',
    'Hip hop',
    'Jazz',
    'Reggae',
    'Rock music',
    'Samba',
    'Specific musical instruments',
    'Drum',
    'Flute',
    'Guitar',
    'Piano',
    'Trumpet',
    'Violin',
  ],
  popular: [
    `Adolf Hitler`,
    `Global warming`,
    `William Shakespeare`,
    `Albert Einstein`,
    `Abraham Lincoln`,
    `Mahatma Gandhi`,
    `The Beatles`,
    `Nelson Mandela`,
    `Elvis Presley`,
    `Nikola Tesla`,
    `Philippines`,
    `Computer`,
    `Walt Disney`,
    `Isaac Newton`,
    `Joseph Stalin`,
    `Black Death`,
    `English language`,
    `Winston Churchill`,
    `Soviet Union`,
    `Schizophrenia`,
    `Islam`,
    `Korean War`,
    `George Washington`,
    `Napoleon`,
    `Greek alphabet`,
    `Christopher Columbus`,
    `Ernest Hemingway`,
    `Periodic table`,
    `Poverty`,
    `Buddhism`,
    `Jimi Hendrix`,
    `Thomas Edison`,
    `Pablo Picasso`,
    `Julius Caesar`,
    `DNA`,
    `Film`,
    `Benjamin Franklin`,
    `Charlie Chaplin`,
    `Vincent van Gogh`,
    `Autism`,
    `Carbon dioxide`,
    `Karl Marx`,
    `Human`,
    `Mona Lisa`,
    `Gautama Buddha`,
    `Newton's laws of motion`,
    `Hinduism`,
    `Wolfgang Amadeus Mozart`,
    `Great Pyramid of Giza`,
    `Machu Picchu`,
    `Mahabharata`,
    `HIV/AIDS`,
    `Nuclear power`,
    `Charles Darwin`,
    `Physics`,
    `Ludwig van Beethoven`,
    `Edgar Allan Poe`,
    `Sigmund Freud`,
    `Neil Armstrong`,
    `Earthquake`,
    `Pollution`,
    `Scientific method`,
    `Dinosaur`,
    `Marie Curie`,
    `Christianity`,
    `Stonehenge`,
    `Communication`,
    `Music`,
    `Meningitis`,
    `Martin Luther`,
    `Economics`,
    `Salvador Dalí`,
    `Animal`,
    `Olympic Games`,
    `Mobile phone`,
    `Romanticism`,
    `Mathematics`,
    `Friedrich Nietzsche`,
    `International Space Station`,
    `Technology`,
    `Hypertension`,
    `Judaism`,
    `Global Positioning System`,
    `Egg`,
    `Aluminium`,
    `Board game`,
    `Capitalism`,
    `Atheism`,
    `Biology`,
    `Shia Islam`,
    `Video game`,
    `Transistor`,
    `Artificial intelligence`,
    `Myocardial infarction`,
    `Alfred Hitchcock`,
    `Religion`,
    `Algorithm`,
    `Speed of light`,
    `Frida Kahlo`,
    `History of India`,
    `Alan Turing`,
    `Computer science`,
    `French language`,
    `Advertising`,
    `Electricity`,
    `Sociology`,
    `Pythagoras`,
    `Agriculture`,
    `Time`,
    `John Locke`,
    `Anthropology`,
    `Management`,
    `Video`,
    `God`,
    `Spice`,
    `Bacteria`,
    `Statistics`,
    `Solar energy`,
    `Sunni Islam`,
    `Spanish language`,
    `Prime number`,
    `Steel`,
    `Mechanical engineering`,
    `Bible`,
    `Chemistry`,
    `Quran`,
    `Nuclear weapon`,
    `Energy`,
    `Immanuel Kant`,
    `Indus Valley Civilization`,
    `German language`,
    `Television`,
    `Renewable energy`,
    `Grand Canyon`,
    `Nut`,
    `Arabic language`,
    `Don Quixote`,
    `Plate tectonics`,
    `Set`,
    `Flower`,
    `Johann Sebastian Bach`,
    `Bird`,
    `Bahá'í Faith`,
    `Sikhism`,
    `Michael Faraday`,
    `Biotechnology`,
    `Literature`,
    `Franz Kafka`,
    `Acid`,
    `Logarithm`,
    `Fish`,
    `Japanese language`,
    `René Descartes`,
    `Petroleum`,
    `Asthma`,
    `Latin`,
    `Metaphysics`,
    `Business`,
    `International Monetary Fund`,
    `Claude Monet`,
    `Ancient Rome`,
    `Hip hop music`,
    `Postmodernism`,
    `Atom`,
    `Adam Smith`,
    `Catholic Church`,
    `Atmosphere of Earth`,
    `Language`,
    `Mammal`,
    `Laser`,
    `Game`,
    `Human body`,
    `Virginia Woolf`,
    `Force`,
    `Calculus`,
    `Electromagnetic radiation`,
    `Law`,
    `Color`,
    `Jainism`,
    `Modernism`,
    `Greek language`,
    `Chinese language`,
    `Taoism`,
    `History`,
    `Five Pillars of Islam`,
    `Pop music`,
    `Ecosystem`,
    `Engineering`,
    `James Cook`,
    `e`,
    `Culture`,
    `Fungus`,
    `Electric motor`,
    `Suicide`,
    `Ontology`,
    `Light`,
    `Plant`,
    `0`,
    `Tourism`,
    `Battery`,
    `Bhagavad Gita`,
    `Human sexuality`,
    `Integer`,
    `Theory of relativity`,
    `Baroque`,
    `Natural selection`,
    `Photography`,
    `World Health Organization`,
    `Portuguese language`,
    `Ecology`,
    `Wind power`,
    `Hubble Space Telescope`,
    `Marco Polo`,
    `Leo Tolstoy`,
    `Russian Empire`,
    `Death`,
    `Life`,
    `Bank`,
    `Nicolaus Copernicus`,
    `Aesthetics`,
    `Species`,
    `Protestantism`,
    `Russian language`,
    `Real number`,
    `Moon landing`,
    `Silicon`,
    `Meditation`,
    `Confucianism`,
    `Napoleonic Wars`,
    `Internal combustion engine`,
    `James Joyce`,
    `Ethnic group`,
    `Sport`,
    `Tree`,
    `J. Robert Oppenheimer`,
    `Frédéric Chopin`,
    `Poetry`,
    `Cryptography`,
    `Pragmatism`,
    `Fossil fuel`,
    `Momentum`,
    `Money`,
    `Ramesses II`,
    `Linguistics`,
    `Shinto`,
    `Community`,
    `Women's suffrage`,
    `Indo-European languages`,
    `Integrated circuit`,
    `Mass media`,
    `Genetics`,
    `Ferdinand Magellan`,
    `Architecture`,
    `Genetic engineering`,
    `Gravitation`,
    `Rumi`,
    `Incandescent light bulb`,
    `Movements for civil rights`,
    `Sleep`,
    `Retail`,
    `Thomas Aquinas`,
    `Catherine the Great`,
    `Nutrition`,
    `Temperature`,
    `Social science`,
    `Function`,
    `Soil`,
    `Metric system`,
    `Supernova`,
    `Salt`,
    `Newspaper`,
    `Satellite`,
    `Vasco da Gama`,
    `Sumer`,
    `Electron`,
    `Gene`,
    `Consciousness`,
    `Number`,
    `Insect`,
    `Finance`,
    `Alcoholism`,
    `Season`,
    `Thermodynamics`,
    `Photon`,
    `Epic of Gilgamesh`,
    `Matter`,
    `Richard Wagner`,
    `State of matter`,
    `Map`,
    `Political science`,
    `Autoimmune disease`,
    `Corporation`,
    `Algebra`,
    `Alphabet`,
    `Gasoline`,
    `Sound`,
    `Fire`,
    `Pyotr Ilyich Tchaikovsky`,
    `Radio`,
    `Achaemenid Empire`,
    `Infinity`,
    `Fyodor Dostoyevsky`,
    `Telecommunication`,
    `Dream`,
    `Bengali language`,
    `Metal`,
    `Radar`,
    `Telephone`,
    `Reptile`,
    `Triangle`,
    `Chemical element`,
    `Extinction`,
    `Fertilizer`,
    `Shamanism`,
    `Amphibian`,
    `Eukaryote`,
    `Mass`,
    `Algae`,
    `Burn`,
    `Eastern Orthodox Church`,
    `Supply and demand`,
    `Vedas`,
    `News`,
    `Motion`,
    `Painting`,
    `Werner Heisenberg`,
    `Mineral`,
    `Antibiotics`,
    `Complex number`,
    `RNA`,
    `Erosion`,
    `Abacus`,
    `Clothing`,
    `Tank`,
    `Infrastructure`,
    `Ravi Shankar`,
    `Steam engine`,
    `Compass`,
    `Assyria`,
    `Electromagnetism`,
    `Constitution`,
    `Archaea`,
    `Organic chemistry`,
    `Proton`,
    `Folk music`,
    `Gender`,
    `Library`,
    `Sphere`,
    `Drug`,
    `Space`,
    `Talmud`,
    `Discrimination`,
    `Heat`,
    `Measurement`,
    `Police`,
    `Niels Bohr`,
    `Infant`,
    `Tang dynasty`,
    `Electronics`,
    `Book`,
    `Macroeconomics`,
    `Dance`,
    `Tax`,
    `Han dynasty`,
    `Short story`,
    `Rational number`,
    `Carl Friedrich Gauss`,
    `Johannes Gutenberg`,
    `Novel`,
    `Biochemistry`,
    `Duke Ellington`,
    `Vacuum`,
    `Physical exercise`,
    `Archaeology`,
    `Sexual orientation`,
    `Golden Rule`,
    `Bronze`,
    `James Clerk Maxwell`,
    `Birth control`,
    `Microscope`,
    `Ion`,
    `Neutrino`,
    `Geometry`,
    `Construction`,
    `Gyroscope`,
    `Climate`,
    `Smoking`,
    `Leonhard Euler`,
    `Mythology`,
    `Akira Kurosawa`,
    `Alloy`,
    `Mining`,
    `Viking Age`,
    `Polygon`,
    `Geology`,
    `Allergy`,
    `Simón Bolívar`,
    `History of mathematics`,
    `Country`,
    `Topology`,
    `Pasteurization`,
    `Gunpowder`,
    `Organism`,
    `Abiogenesis`,
    `Sexism`,
    `Circle`,
    `Manufacturing`,
    `Wave`,
    `Natural number`,
    `Camera`,
    `Microeconomics`,
    `Lens`,
    `Cyrillic script`,
    `Lung`,
    `Fraction`,
    `History of the Earth`,
    `Indigenous peoples`,
    `Anesthesia`,
    `Crime`,
    `Glacier`,
    `Arabic alphabet`,
    `Scramble for Africa`,
    `Herodotus`,
    `Sculpture`,
    `Pendulum`,
    `Volume`,
    `Vaccine`,
    `Carl Linnaeus`,
    `Industry`,
    `Gottfried Wilhelm Leibniz`,
    `House`,
    `Engine`,
    `Clock`,
    `Happiness`,
    `Currency`,
    `Magnetism`,
    `Fear`,
    `Orchestra`,
    `Justice`,
    `Seed`,
    `Arab–Israeli conflict`,
    `Dam`,
    `Spirituality`,
    `Chemical reaction`,
    `Outer space`,
    `History of the world`,
    `Jet engine`,
    `Botany`,
    `Structure of the Earth`,
    `Prose`,
    `Deity`,
    `Grammar`,
    `State`,
    `Soul`,
    `Rock`,
    `Neutron`,
    `Sword`,
    `Musical theatre`,
    `Electrolysis`,
    `Natural rubber`,
    `Fiction`,
    `Ancient history`,
    `Age of Discovery`,
    `Bridge`,
    `Knife`,
    `Textile`,
    `Calculator`,
    `Molecule`,
    `Arctic`,
    `Rocket`,
    `Miguel de Cervantes`,
    `Zoology`,
    `Standard Model`,
    `Base`,
    `Scientific revolution`,
    `European colonization of the Americas`,
    `Tanakh`,
    `Surgery`,
    `Popular culture`,
    `Shaka`,
    `Musical instrument`,
    `Year`,
    `Drawing`,
    `Comedy`,
    `Hatshepsut`,
    `Optics`,
    `Chemical compound`,
    `Catalysis`,
    `Tool`,
    `Lake`,
    `Heredity`,
    `Afterlife`,
    `Islamic Golden Age`,
    `Wheel`,
    `Theocracy`,
    `Dmitri Mendeleev`,
    `Singing`,
    `Kahlil Gibran`,
    `Artillery`,
    `Chinese characters`,
    `Theatre`,
    `Neolithic Revolution`,
    `El Greco`,
    `Visual arts`,
    `Drinking water`,
    `Simple machine`,
    `Employment`,
    `Chemical bond`,
    `East–West Schism`,
    `Female`,
    `Hydropower`,
    `Space exploration`,
    `Antoine Lavoisier`,
    `Writing`,
    `Entertainment`,
    `Zoroaster`,
    `Pericles`,
    `Trade`,
    `Hospital`,
    `Pottery`,
    `Mesoamerica`,
    `Journalism`,
    `Cooking`,
    `Animal husbandry`,
    `Giuseppe Verdi`,
    `Telescope`,
    `Exponentiation`,
    `Museum`,
    `Anger`,
    `Metallurgy`,
    `Printing`,
    `Mary Wollstonecraft`,
    `Earth science`,
    `Sundial`,
    `Upanishads`,
    `Tragedy`,
    `Adi Shankara`,
    `Calendar`,
    `Masonry`,
    `Division`,
    `History of Europe`,
    `Privacy`,
    `Esotericism`,
    `Magazine`,
    `Ageing`,
    `Abolitionism`,
    `Hildegard of Bingen`,
    `Sanitation`,
    `Theravada`,
    `Rail transport`,
    `Adult`,
    `Molecular biology`,
    `Domestication`,
    `Prayer`,
    `Publishing`,
    `Hunting`,
    `Computing`,
    `Antonie van Leeuwenhoek`,
    `Male`,
    `History of science`,
    `History of agriculture`,
    `Weapon`,
    `Reason`,
    `Subatomic particle`,
    `Number theory`,
    `Theism`,
    `Refrigeration`,
    `Broadcasting`,
    `Arithmetic`,
    `Dimension`,
    `Environmentalism`,
    `Card game`,
    `Hokusai`,
    `Word`,
    `Bow and arrow`,
    `History of Africa`,
    `Mathematical optimization`,
    `Mahayana`,
    `Day`,
    `Navigation`,
    `Classical mechanics`,
    `Property`,
    `Speech`,
    `Series`,
    `Orbit`,
    `Roald Amundsen`,
    `Combinatorics`,
    `Leif Erikson`,
    `Hammurabi`,
    `Natural satellite`,
    `Multiplication`,
    `Arch`,
    `David Hilbert`,
    `Firearm`,
    `Vajrayana`,
    `Medical imaging`,
    `Existence`,
    `Polyhedron`,
    `Particle physics`,
    `Road`,
    `Yangtze`,
    `History of medicine`,
    `The arts`,
    `Philosophy of science`,
    `Guru Granth Sahib`,
    `Weak interaction`,
    `Conic section`,
    `Gothic art`,
    `Recreation`,
    `Performing arts`,
    `Explosive material`,
    `History of technology`,
    `Ancient Greek philosophy`,
    `Limit`,
    `Plane`,
    `Mail`,
    `The Renaissance`,
    `Canal`,
    `Strong interaction`,
    `Belief`,
    `Muḥammad ibn Mūsā al-Khwārizmī`,
    `Civil liberties`,
    `Pierre-Simon Laplace`,
    `Inorganic chemistry`,
    `Equation`,
    `Analytic philosophy`,
    `Latin script`,
    `Line`,
    `Addition`,
    `Candle`,
    `Toy`,
    `Nagarjuna`,
    `Physical chemistry`,
    `Hindustani language`,
    `Sergei Eisenstein`,
    `Fortification`,
    `Shape`,
    `History of art`,
    `Mathematical analysis`,
    `Factory`,
    `Semiconductor device`,
    `Variable`,
    `Job`,
    `Land`,
    `Subtraction`,
    `Medieval philosophy`,
    `Humanitarianism`,
    `Mathematical proof`,
    `History of the Middle East`,
    `Contemporary philosophy`,
    `Western philosophy`,
    `Physical cosmology`,
    `Worship`,
    `Shahnameh`,
    `Numerical digit`,
    `Personal name`,
    `Good and evil`,
    `Eastern philosophy`,
    `History of Asia`,
    `Jābir ibn Hayyān`,
    `nth root`,
    `Stove`,
    `Tower`,
    `Nuclear technology`,
    `Point`,
    `History of South America`,
    `History of North America`,
    `Political freedom`,
    `Fishing industry`,
    `Personal life`,
    `Imperial and US customary measurement systems`,
    `Major trauma`,
    `Brahmic scripts`,
    `Shen Kuo`,
    `History of East Asia`,
    `End of Communism in 1989`
  ]
};

let all = Object.keys(pages).reduce((arr, k) => {
  arr = arr.concat(pages[k]);
  return arr;
}, []);

// all = all.reduce(function(h, a) {
//   h[a] = true;
//   return h;
// }, {});
// let more = require('/Users/spencer/Desktop/more.js');
// more.forEach((s) => {
//   if (!all[s]) {
//     console.log(s);
//   }
// });
console.log(all.length);
